name: CI with SonarCloud

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  # llm-stack-monitor-frontend: Vite (React.js) Build & SonarCloud Analysis
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0"  # updated Node.js version

      - name: Install dependencies (Vite - React)
        run: |
          cd llm-stack-monitor-frontend
          npm ci

      - name: Run tests (React - Vite)
        run: |
          cd llm-stack-monitor-frontend
          npm run test -- --coverage

      - name: Generate LCOV report
        run: |
          cd llm-stack-monitor-frontend
          # Assuming Vite tests output coverage in coverage/lcov.info
          mkdir -p lcov-report
          cp coverage/lcov.info lcov-report/lcov.info

      - name: Upload coverage to SonarCloud (React)
        run: |
          cd llm-stack-monitor-frontend
          echo "React coverage prepared."

  # llm-stack-monitor-backend: Django Build & SonarCloud Analysis
  django:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies (Django)
        run: |
          cd llm-stack-monitor-backend
          pip install -r requirements.txt

      - name: Run tests (Django)
        run: |
          cd llm-stack-monitor-backend
          pytest --cov=. --cov-report=xml:coverage.xml

      - name: Upload coverage to SonarCloud (Django)
        run: |
          cd llm-stack-monitor-backend
          echo "Django coverage prepared."

  # SonarCloud Analysis
  sonarcloud:
    runs-on: ubuntu-latest
    needs: [react, django]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SonarCloud Scanner
        run: |
          npm install -g sonar-scanner

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=001am \
            -Dsonar.organization=SOHAM_PANCHAL \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.javascript.lcov.reportPaths=llm-stack-monitor-frontend/lcov-report/lcov.info \
            -Dsonar.python.coverage.reportPaths=llm-stack-monitor-backend/coverage.xml \
            -Dsonar.sources=llm-stack-monitor-frontend/src,llm-stack-monitor-backend \
            -Dsonar.exclusions=llm-stack-monitor-frontend/dist/**,llm-stack-monitor-backend/migrations/**

